plausible/docs

docs/nextjs-integration.md

Hi!
I created https://github.com/4lejandrito/next-plausible to ease the integration with NextJS. I thought it might be a good idea to add it to your docs.
I really like the simplicity and ethics of Plausible. Thanks for that!

Adding instructions to integrate with nextjs

---

docs/nextjs-integration.md

Those `jsx` bits must go in the same line. The site gets no highlighting if they don't.

Fixing syntax highlighting

---

docs/self-hosting.md

Adds a missing `to` in a sentence. Just a small fix, but I noticed it while reading the documentation.

Fix small typo

---

docs/self-hosting-configuration.md

These worked for me, though FWIW Phoenix didn't find the new environment variables with a simple `docker-compose restart plausible`. Instead, I had to run `docker-compose stop && docker-compose up -d`.

Add setup instructions for Twitter integration

---

docs/community-integrations.md

I built a Vue.js plugin and Nuxt.js module to easily integrate [plausible-tracker](https://github.com/plausible/plausible-tracker). Added them to the community-integrations docs page.

Add Vue.js plugin and Nuxt.js module

---

docs/self-hosting.md

The previous link was missing base `/docs` and not pointing to the correct page.

Update configuration link in self-hosting.md

---

docs/stats-api.md

Hello!
I have fixed the API example on realtime visitors. The base route was erroneously only with `/api/v1`, not with `/api/v1/stats`.

Fix API example on real time visitors

---

docs/self-hosting-configuration.md
docs/self-hosting.md

I updated the docs to note that when you log in for the first time with the admin user, you have to verify them using your server's SMTP settings or update it manually in the database. I ran into this issue when self-hosting plausible, and I found the solution in a github discussion (https://github.com/plausible/analytics/discussions/809). I thought it would be useful to include it in the docs themselves. Feedback appreciated.

updating self-hosting instructions

---

docs/self-hosting-configuration.md

Since v1.3.0 (or, more specifically, https://github.com/plausible/analytics/pull/906) Plausible ships its own country database.
Update the docs, leaving previous instructions example of getting another source of country data.

Mention geo database shipped with plausible

---

docs/proxy/guides/cloudflare.md

One of the issues with the CNAME setup was that you could receive first-party cookies of the website domain. It'd be better to not allow this to happen with the proxy setup.

remove cookies in CF worker

---

docs/self-hosting-configuration.md

These parameters were added in this PR: https://github.com/plausible/analytics/pull/1073

Added CLICKHOUSE_FLUSH_INTERVAL_MS and CLICKHOUSE_MAX_BUFFER_SIZE to self-hosting configuration doc

---

docs/proxy/guides/cloudflare.md
docs/proxy/guides/netlify.md

Fixed some small mistakes. See commits for details.
It's mentioned that /api/event should return 202 but the Netlify redirect has 200. Shouldn't it be 202?

Improvements to proxy documentation

---

docs/proxy/guides/nextjs.md

When we enable trailing slash, NextJS first routes `/api/event` to `/api/event/` and then checks for `rewrites`
I've lost a full day of analytics due to this. 😅

Add comment in code for trailingSlash: true in config

---

docs/self-hosting.md

I was confused by the 
> Starts the server on port 80
in https://plausible.io/docs/self-hosting, shouldn't this be 8000? (guess so)
Also reformatted bash references for easier copy & paste

Should the correct port be 8000?

---

docs/proxy/guides/nginx.md

I found that to make it work on self-hosted domains of plausible I needed extra Nginx instructions to make it work, so here I'm adding those extra instructions for a better documentation

Adding extra instruction in case of self-hosting

---

docs/proxy/guides/nginx.md

[As detailed in this comment](https://github.com/plausible/analytics/discussions/1293#discussioncomment-1270234) the `/var/run/nginx-cache` directory needs to exist in order for the recommended `proxy_cache` setup to work, this wasn't clear from the documentation so submitting a suggested tweak here for those who run into the same issue down the line.

Add `proxy_cache` clarification to nginx guide

---

docs/custom-domain.md

Unless we really mean that custom domains reduce in value over time.

Quick fix: "depreciated" -> "deprecated"

---

docs/outbound-link-click-tracking.md

This is an undocumented issue/limitation of the current tracker implementation. There has been some discussion in plausible/plausible-tracker#12 but no fix yet. If I understand correctly, plausible/plausible-tracker#16 could solve this.  
With this PR I'd like to propose adding a warning to the docs to prevent others from tripping over this.
Thank you for plausible! It's awesome to be able to use such a simple service without having to bother with consent banners or worry about Google trackers :heart:

Document potentially link-breaking behaviour of outbound link tracking

---

docs/custom-locations.md

`linl` should be `link` in code.

Fix typo in documentation

---

docs/stats-api.md

Previously, `name%3D%3D%2Download` would be decoded to `name==-ownload`.
Now, `name%3D%3DDownload` decodes to `name==Download`.

fix: Remove `%2` from custom events breakdown API url

---

docs/self-hosting-configuration.md

It's my understanding that Twitter integration got removed recently right? 
In https://github.com/plausible/analytics/commit/4d0bc61ffdd1a9e8f03bcd37afd66c2f6079ceff to be exact.
The self-hosting documentation is still mentioning the non-working setup.

Remove deprecated Twitter integration instructions

---

docs/integration-guides.md
docs/plausible-analytics-reviews.md

Hi!
A while back I wrote: https://www.lekoarts.de/gatsby/using-deferred-static-generation-with-analytics-tools
I shows how to create a custom source plugin for Plausible in Gatsby and use that to conditionally defer pages (a new feature in Gatsby 4). Disclaimer: I work at Gatsby.
If you feel like this fits into this page, I'd be happy to see it merged. If not, not a problem :)
Thanks for Plausible!

chore(docs): Add Gatsby DSG post to integration-guides

---

docs/stats-api.md

Without these, your examples fail because the ampersands get grabbed by the shell and spawn background processes. Not ideal. :)

Add single quotes around curl examples

---

docs/proxy/guides/nginx.md

Just bumped in this little issue while configuring a VPS to self-host plausible.
The issue on startup of nginx after a reboot:
```
root@analytics:~# service nginx status
Mar 25 08:58:05 analytics systemd[1]: Starting A high performance web server and a reverse proxy server...
Mar 25 08:58:06 analytics nginx[724]: nginx: [emerg] mkdir() "/var/run/nginx-cache/jscache" failed (2: No such file or directory)
Mar 25 08:58:06 analytics nginx[724]: nginx: configuration file /etc/nginx/nginx.conf test failed
Mar 25 08:58:06 analytics systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
Mar 25 08:58:06 analytics systemd[1]: nginx.service: Failed with result 'exit-code'.
Mar 25 08:58:06 analytics systemd[1]: Failed to start A high performance web server and a reverse …
```

Persist /var/run/nginx-cache on reboots

---

docs/integration-guides.md

npm should always be lower-case
REF: https://docs.npmjs.com/policies/trademark

npm capitalization fix

---

docs/self-hosting-configuration.md

From plausible/analytics#1190.
Also explain how to fully lock down the services that Plausible requires (`beam` inter-node communication and `epmd`).

Document `LISTEN_IP` environment variable

---

docs/self-hosting-configuration.md

Usually I don't have a Elixir environment at handy to generate one, but `openssl` is always installed.

docs(self-hosting): add alternative to generate a secret

---

docs/self-hosting.md

Relates to https://github.com/plausible/hosting/pull/24

Adds note to make container port local only, after setting up a reverse proxy

---

docs/self-hosting.md

Per offline talk with clickhouse developers, clickhouse-client will never be updated as it's part of the server package, and the change is the recommended way of using it. Changing the invocation from clickhouse-client to clickhouse-server allows it to work under arm64, which became possible recently.

Run clickhouse-server instead of clickhouse-client

---

docs/stats-api.md

1) add information about wildcard support in Stats API
2) remove mention of `event:name==pageview` from pageview goals section in Stats API docs

add information about wildcard support

---

docs/stats-api.md

Added a simple "try it yourself" example to fetch the number of visits/sessions from the Stats API.

add sessions curl example

---

docs/custom-locations.md

Some explanation of what exactly this does and why it's necessary.
When sending the pageview with `plausible('pageview', {u: 'https://mysite.com/my_location'})`, Plausible will not know about any query parameters - this exact URL is what will be sent to Plausible.
But what we can do, is use the **actual** location of the page (`location`), get the entire query string (e.g. "?utm_source=Google&custom=stuff") from `location.search` and append it to the custom URL provided by the user. This will not affect the page paths in any way, as no query parameters are shown in the Pages report. The only effect is what we would expect - query params that Plausible uses for source acquisition can be tracked.

Instruct to keep query params in the URL with manual extension

---

docs/self-hosting-configuration.md

This PR adds instructions to enable GA imports on a self-hosted instance.

add self-hosting GA-imports configuration

---

docs/discourse-integration.md

Hi there!
I couldn't get these instructions to work as-is, and it turns out that there's a cross-site protection in Discourse that requires you to add another setting - thought I'd contribute this to make sure others have the full picture. 😄

Add how to add plausible.io to the XSS protection

---

docs/integration-guides.md

These pull requests updates the Gatsby Plugin maintainer website url since aquil.io is no longer available.
cc: @ccummings

Update Gatsby Plugin maintainer url

---

docs/self-hosting-configuration.md

As the title suggested, while I was deploying my own instance, I found that Google now requires the consent screen to be configured before any client credentials can be created.

Configure consent screen before create client credentials

---

docs/custom-event-goals.md

We can use HTML tags to mark headings instead of markdown - then they won't show up in the sidebar menu.

Keep collapsed headings out of sidebar view

---

docs/script-extensions.md

As we will be disabling TLS 1.0 and 1.1 support, the script script.compat.js will not work on Internet Explorer versions older than version 11 when served from our CDN.

Update compatibility info about script.compat.js

---

docs/self-hosting-configuration.md
docs/self-hosting.md

This PR updates the self-hosted docs for `v2` release (together with https://github.com/plausible/docs/pull/396).

v2 self-hosted changes

---

docs/self-hosting-configuration.md

Added better docs for self hosters to explain how to use the new email adapters.
This PR also provides docs for this PR https://github.com/plausible/analytics/pull/2935 that adds Mailgun BASE_URI support.

Added docs for the new Email Adapters

---

docs/self-hosting.md

As promised in https://github.com/plausible/analytics/discussions/1459#discussioncomment-6687216
> Maybe it's worth adding this to the official documentation, so you don't have to worry and go through links looking for solutions, you know, not what you want to do.

mention releases page in 'Version management' section

---

docs/stats-api.md

Documentation for the `event:goal` property in Stats API. Should be merged once https://github.com/plausible/analytics/pull/3718 is live.

Document `event:goal` in Stats API

---

docs/stats-api.md

We suggest users use SITE_ID as an environment variable in these docs, but the example commands use single quotes, meaning that the variable wouldnt get expanded.
This bit me when trying to answer a customer question, so making everything more consistent

Stats API: Use double quotes in curl commands.

---

docs/stats-api.md

This reverts commit 964eeea728674a7c9f148d08987ed30cc441a97d, reversing changes made to 7cec37bdc91f129e7eff29974887c239ec07106f.
There are known issues with the conversion rate metric that we want to resolve before adding it into the public API

Revert "Merge pull request #461 from plausible/stats-api-cr"

---

docs/stats-api.md

Reapplying the documentation for the conversion rate metric in Stats API.
This reverts commit 00c7b48032a3480864494926e24b8a73f7df4212, reversing changes made to 6cd039cab221dc2129f550c49684cd96f602085a.

Reapply Stats API conversion rate docs

---

docs/csv-import.md

This PR removes references to time on page in CSV exports/imports as it's no longer being exported / imported. 
Related: https://github.com/plausible/analytics/pull/4051

drop time on page from CSV docs

---

docs/stats-api.md

~Sort of depends on https://github.com/plausible/analytics/pull/4110 (best to merge this documentation update once the fixes are already in production).~
Should go together with https://github.com/plausible/analytics/pull/4116

Add description of `with_imported` support to Stats API docs

---

docs/stats-api.md

**The properties information table missed a vertical pipe separator in the `visit:browser_version` row.**
Also, adds spaces to the other rows to match the format.

Fix table column separator for properties

---

docs/apps-widgets.md
docs/integration-guides.md

…and add Tally for Linux. These feel like they belong on their own page instead of stuck at the bottom of the integrations page, since they're ways to access your Plausible stats from another platform, _not_ ways to integrate Plausible Analytics tracking into a site/app/etc.
As suggested at https://github.com/plausible/analytics/discussions/4141#discussioncomment-9554400

integration-guides: Move apps/widgets to own page

---

docusaurus.config.js

Tracking on the docs page was broken ~3 weeks ago, when I deployed a new tracking script. The script src was working locally with the path `js/tracking.js`, but on production, it requires the docs subfolder prefix.
Currently the request is made to https://plausible.io/js/tracking.js which is indeed a 404. The correct url is https://plausible.io/docs/js/tracking.js.

Fix tracking js file url

---

docs/stats-api-v2.md

Examples are interactive and cant be pre-built by docusaurus

Fix examples-related `npm run build` failure

---

docs/stats-api-v2.md

If you are entering time you will need to pass it in the proper format.

Change date format in date range example

---

src/js/apiv2-editor.tsx
src/js/apiv2-playground.tsx

Currently, no feedback is given to the user when they run an invalid JSON query in playground.
This is related to weirdness in JSON body parsing in the main repo. By setting `Accept` header, this issue goes away and we provide proper feedback.
Ref: https://3.basecamp.com/5308029/buckets/26383192/card_tables/cards/7898119573

Stats API Playground: Show errors when invalid JSON

---

docs/integration-guides.md

The links in the documentation pointed to an archived repository. The fixed links point to the currently maintained one.

Fix Bridgetown plugin links

---

docs/stats-api.md
src/js/apiv2-examples/filtering-case-insensitive-query.json
src/js/apiv2-examples/filtering-case-insensitive-response.json
src/js/examples.tsx

Companion to https://github.com/plausible/analytics/pull/4863

Docs for case insensitivity

---

docs/discourse-integration.md
docs/stats-api.md
src/js/apiv2-examples/response-meta.json
src/js/apiv2-examples/revenue-metrics-query.json
src/js/apiv2-examples/revenue-metrics-response.json
src/js/apiv2-examples/revenue-warning-query.json
src/js/apiv2-examples/revenue-warning-response.json
src/js/examples.tsx

Also fixes the build along the way.
Some screenshots:

Revenue metrics in APIv2

---

docs/data-pipelines.md

[Applausible](https://apps.apple.com/us/app/applausible-for-plausible/id6737839249) is a third-party client app for viewing Plausible Analytics data on iOS. It offers an optimized experience for both iPhone and iPad. The app also allows users to view their data directly from various home widgets.

Add Applausible iOS app

---

static/js/tracking.js

Companion PR to https://github.com/plausible/analytics/pull/5005
Tested locally by modifying the file so:
```diff
--- a/static/js/tracking.js
+++ b/static/js/tracking.js
@@ -1,9 +1,10 @@
const script = document.createElement('script')
script.defer = true
-script.dataset.domain = 'plausible.io'
+script.dataset.domain = 'dummy.site'
script.dataset.allowFetch = 'true'
-script.src = 'https://plausible.io/js/script.pageview-props.pageleave.js'
+script.dataset.apiHost = 'http://localhost:8000'
+script.src = 'http://localhost:8000/js/script.local.pageleave.pageview-props.js'
script.setAttribute('event-browser_language', navigator.language || navigator.userLanguage)
document.getElementsByTagName('head')[0].appendChild(script)
```

Add fetch-with-keepalive support to docs

---

static/js/tracking.js

`pageleave` variant code is now in main script - we can remove the usage.

Update tracking script variant

---

docs/stats-api.md

Hello!
While writing TypeScript types for the `filters` of the query I found that the documentation had typos in them. I validated this by also looking at the example https://plausible.io/docs/stats-api#example-filtering.

fix: Correct logical operations in stats api

---

docs/sites-api.md

Ref https://github.com/plausible/analytics/pull/5205

Document Sites API `guests` resource

---

docs/error-pages-tracking-404.md
docs/google-tag-manager.md

Setting props.path is not necessary after https://github.com/plausible/analytics/pull/5559. It is automatically synced to be the same as the resolved pathname of the event.

Update 404 tracking examples
