- docs/authors.md
Hi @ukutaht / @metmarkosaric 
Thanks for adding me to your docs 🥰  I would like to filter out the users visiting to my blog. Now that I have my own instance, I added a reference source. It would help me out a ton! 
Cheers!
Signed-off-by: Chandra Tungathurthi <tckb@tgrthi.me>
> Request: Adding reference source to my blog

- docs/community-integrations.md
> Add "ignore tracking on certain pages" for plausible-hugo

- docs/plausible-script.md
It should help people to use PA with less technical steps.
> Add a link to community integration on the install page.

- docs/community-integrations.md
Hey @ukutaht and @metmarkosaric,
thanks for pushing privacy on the web forward! 
I've made a small lib to allow integration in VuePress sites. 
Let me know if you got any questions!
Cheers,
Peter
> Adding VuePress integration in

- docs/self-hosting-configuration.md
Configuratation ➙ Configuration
> Typo in docs

- docs/self-hosting-configuration.md
This worked for me to authorize with Google on my self-hosted instance.
> Add explanation of Google Search Integration config

- docs/community-integrations.md
Hi, 
I created a simple plugin which integrates plausible into a Gridsome site. 
Maybe it is also helpful for others.
> Add Gridsome Plugin

- docs/self-hosting.md
Hi, was going through the self-hosted documentation. Spotted and corrected a couple of minor spellings, nothing major :)
> two minor spell checks

- docs/authors.md
> Adds UTM Tags to authors.md

- docs/custom-domain.md
What do you think? Would it be helpful to include a link to an online cname lookup tool?
> Adds instructions to check the custom domain configuration

- docs/keyboard-shortcuts.md
From discussion in plausible/analytics#707
(The larger diff is because the file originally had trailing spaces)
> Adds new keybindings for time selection

- docs/keyboard-shortcuts.md
I think the wording for this could be a bit better, perhaps with a screenshot or something - but I dunno.
> Adds docs for site switching keybinds

- docs/self-hosting-configuration.md
this might help some edge cases
> add explicit db connection string examples

- docs/self-hosting.md
happy to improve on the wording styles, and content of the information
> add caveats of external databases

- docs/custom-event-goals.md
Tracking events with the use of data attributes
Related to: https://github.com/plausible/analytics/discussions/944
> Add event tracking to links and forms from HTML

- docs/integration-guides.md
Available in the new v1.11.0 version
> Add 404 custom goal for hugo

- docs/self-hosting-configuration.md
Docs PR for https://github.com/plausible/analytics/pull/1052
> Document env-vars `DATABASE_SOCKET_DIR` & `DATABASE_NAME`

- docs/404-error-pages-tracking.md
- docs/carrd-integration.md
- docs/custom-domain.md
- docs/custom-event-goals.md
- docs/discourse-integration.md
- docs/docusaurus-integration.md
- docs/excluding-pages.md
- docs/hash-based-routing.md
- docs/internal-link-click-tracking.md
- docs/javascript-snippet.md
- docs/outbound-link-click-tracking.md
- docs/plausible-script.md
- docs/proxy/guides/nginx.md
Some trailing space where removed by my editor (VSC) to comply for md lint
> replace `async defer` by `defer` for <script> + misc linter

- docs/proxy/guides/netlify.md
Update Netlify integration guide to clarify an additional configuration required to support proxying requests via Netlify.
This caught me up and confused me until I realised what the conflict was caused by.
> Highlight problematic Netlify config

- docs/proxy/guides/nextjs.md
Following the steps from https://github.com/4lejandrito/next-plausible#proxy-the-analytics-script.
> Documenting how to proxy the script using next-plausible

- docs/integration-guides.md
I haven't yet integrated all API calls, but I feel it can already be useful
> Add reference to wrapper for the R programming language

- docs/hugo-integration.md
- docs/integration-guides.md
> Update hugo configuration

- docs/export-stats.md
This updates the docs to reflect the changes made in https://github.com/plausible/analytics/pull/1387
> Update stats export page with zip file download

- docs/custom-locations.md
- docs/script-extensions.md
Documents the custom location feature implemented in plausible/analytics#1479.
> Updates documentation for custom locations

- docs/self-hosting.md
> Fix typo in self hosting docs page

- docs/stats-api.md
Docs for https://github.com/plausible/analytics/pull/1529
> Add events metric to breakdown endpoint

- docs/slack-reports.md
> Spelling update

- docs/guided-tour.md
> Spelling updates

- docs/google-search-console-integration.md
> Grammar update

- docs/filters-segments.md
analyse to analyze like the rest of the doc
> Spelling consistency

- docs/metrics-definitions.md
multiple consistency updates and grammar changes.
Also - consider making this list alphabetical for easier scroll searching
> Grammar updates

- docs/outbound-link-click-tracking.md
> Spelling and grammar updates

- docs/stats-api.md
> Grammar and spelling updates

- docs/manual-link-tagging.md
- docs/metrics-definitions.md
- docs/stats-api.md
- docs/top-referrers.md
- docs/your-plausible-experience.md
https://github.com/plausible/docs/pull/134
> PR 134 - conflicts resolved

- docs/proxy/guides/nextjs.md
- docs/proxy/guides/vercel.md
- docs/proxy/introduction.md
- sidebars.js
See: https://github.com/plausible/docs/issues/169
> Add page for Vercel proxy

- docs/self-hosting.md
Run the docker-compose command in detached mode
> Adjust MaxMind Docker-Compose Command

- docs/hash-based-routing.md
Making a minor adjustment, which now forms a complete sentence.
> Minor clarification to sentence

- docs/proxy/guides/caddy.md
Fix formatting to conform with `caddy fmt`.
Also clarify where to add the code snippet.
I had been struggling so I thought we should  clarify the docs for the future generation :)
> Improve caddy proxy instructions

- docs/filters-segments.md
Documents the change added [here](https://github.com/plausible/analytics/pull/1799)
> Mention the "contains" filter type

- docs/file-downloads-tracking.md
Formatted the file types as code in the default list
> Readability improvement

- docs/self-hosting.md
> Fix "Github" typo

- docs/integration-guides.md
> Not available anymore

- docs/script-extensions.md
Found on: https://plausible.io/docs/script-extensions#all-our-script-extensions
> Fix a couple of broken internal links

- docs/integration-guides.md
worked this out while updating our Read The Docs install.  Wanted to pass it on
> sphinx integration

- docs/proxy/guides/fresh.md
- docs/proxy/introduction.md
Here's an easy way to set up a proxy w/ [Fresh](https://fresh.deno.dev/).
> Add Fresh Proxy Docs

- docs/embed-dashboard.md
Merge together with: https://github.com/plausible/analytics/pull/2148
> Document width=manual mode for embeds

- docs/stats-api.md
Also mention custom event goals
> Stats API improve event:name description

- docs/sites-api.md
> Fixed simple typo I found :)

- docs/events-api.md
Related to: https://github.com/plausible/analytics/pull/2536
> Update Events API documentation

- docs/slack-reports.md
Edited instructions to match the new Slack UI
> Edit slack-reports.md

- docs/stats-api.md
To be merged once we have tested the new metric under a feature flag.
> add docs for 'pages_per_visit' (Stats API)

- docusaurus.config.js
Let's have a dark mode switch?
> add darkmode

- docs/custom-event-goals.md
Ref: https://github.com/plausible/analytics/issues/2851
> Warn about tagged-events limitation (form id/name="submit")

- docs/authors.md
Hi there, 
I'm doing some maintenance work  on my blog  (now unmaintained). I've given a new subdomain to my blog and want to update it in your contribution page. Thanks for the bump!  
Best, 
Chandra
> Updating tckb's personal blog baseurl

- docs/custom-event-goals.md
@bogplau, I think this could be mentioned in the Webflow docs too. I believe we could simplify the instructions for tracking buttons and link clicks.
> Note about the option to use `--` instead of `=`

- docs/integration-guides.md
> fix: vue and nuxt link

- docs/change-email.md
Related to change in account email update flow introduced in https://github.com/plausible/analytics/pull/3388
> Update section on changing email address in Plausible dashboard

- docs/troubleshoot-integration.md
Sorry if this PR is too small, but this small typo annoyed me to no end.
Thank you for your consideration.
> Fix tiny typo on "How to check if Plausible is working"

- docs/events-api.md
Add info how to debug requests when using the events api
> Add info to debug requests

- docs/self-hosting.md
As requested in https://github.com/plausible/analytics/issues/3610
> note arm64 support

- docs/stats-api.md
https://github.com/plausible/analytics/pull/3505
> Document adding events support to timeseries

- docs/integration-guides.md
This PR adds a Sylius integration to the list of integrations
> Add Sylius

- docs/self-hosting.md
This PR adds a note about MaxMind setup requiring more RAM as requested in https://github.com/plausible/analytics/discussions/3607#discussioncomment-7816142
> add note about MaxMind's GeoLite2-City requiring more RAM

- docs/shopify-integration.md
> docs: clarify custom props in shopify how to

- docs/stats-api.md
Depends on https://github.com/plausible/analytics/pull/4008
> Expose `event:hostname` property

- docs/integration-guides.md
Link was broken but it works now!
> fix: broken Plausible Analytics integration link in integration-guide

- docs/file-downloads-tracking.md
Keeps docs up to date with this PR: https://github.com/plausible/analytics/pull/4085
> Add dmg extension to file-downloads-tracking.md

- docs/csv-import.md
With custom props, it's ten tables now.
> update tables count in csv-import doc

- docs/sites-api.md
To go along with https://github.com/plausible/analytics/pull/4302
> Document extended Sites API

- docs/stats-api.md
Should be merged once https://github.com/plausible/analytics/pull/4451 is live.
> Rename `date` interval to `day` in Stats API

- docs/stats-api-v2.md
Reverts plausible/docs#534
The fix did not work as intended, reverting.
> Revert "Fix examples-related `npm run build` failure"

- docs/events-api.md
- docs/sites-api.md
- docs/stats-api-playground.md
- docs/stats-api-v2.md
- docs/stats-api.md
- package-lock.json
- package.json
- sidebars.js
- src/css/custom.css
- src/js/api-helpers.tsx
- src/js/apiv2-editor.tsx
- src/js/apiv2-example.tsx
- src/js/apiv2-playground.tsx
- src/js/examples.tsx
- src/js/sites.tsx
- tsconfig.json
This PR follows up on https://github.com/plausible/docs/pull/532 by:
1. Adding typescript to our docs
2. Adding a new "Stats API v2 playground page"
The UI/UX on this is pretty anemic - would gladly accept volunteers to help improve it :)
> Typescript, Stats API v2 playground

- docs/traffic-spikes.md
Waiting for https://github.com/plausible/analytics/pull/5251
> Add top pages in traffic spike email

- docs/keyboard-shortcuts.md
- docs/stats-api.md
Depends on https://github.com/plausible/analytics/pull/5301
> Last 90 -> 91 days

- docs/custom-props/for-custom-events.md
- docs/events-api.md
- docs/metrics-definitions.md
WIP.
Companion to https://github.com/plausible/analytics/pull/5295
> Documentation for non-interactive custom events

- docs/integration-guides.md
Ref: https://3.basecamp.com/5308029/buckets/42034199/card_tables/cards/8950087460
> Update npm package link
